using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class CodeSyncModel {
    [RealtimeProperty(4, true, true)]
    private bool _activated;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class CodeSyncModel : RealtimeModel {
    public bool activated {
        get {
            return _activatedProperty.value;
        }
        set {
            if (_activatedProperty.value == value) return;
            _activatedProperty.value = value;
            InvalidateReliableLength();
            FireActivatedDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(CodeSyncModel model, T value);
    public event PropertyChangedHandler<bool> activatedDidChange;
    
    public enum PropertyID : uint {
        Activated = 4,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _activatedProperty;
    
    #endregion
    
    public CodeSyncModel() : base(null) {
        _activatedProperty = new ReliableProperty<bool>(4, _activated);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _activatedProperty.UnsubscribeCallback();
    }
    
    private void FireActivatedDidChange(bool value) {
        try {
            activatedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _activatedProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _activatedProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Activated: {
                    changed = _activatedProperty.Read(stream, context);
                    if (changed) FireActivatedDidChange(activated);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _activated = activated;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
