using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;
[RealtimeModel]
public partial class MatchSyncModel {
	[RealtimeProperty(1, true, true)]
    private bool _lit;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class MatchSyncModel : RealtimeModel {
    public bool lit {
        get {
            return _litProperty.value;
        }
        set {
            if (_litProperty.value == value) return;
            _litProperty.value = value;
            InvalidateReliableLength();
            FireLitDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(MatchSyncModel model, T value);
    public event PropertyChangedHandler<bool> litDidChange;
    
    public enum PropertyID : uint {
        Lit = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _litProperty;
    
    #endregion
    
    public MatchSyncModel() : base(null) {
        _litProperty = new ReliableProperty<bool>(1, _lit);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _litProperty.UnsubscribeCallback();
    }
    
    private void FireLitDidChange(bool value) {
        try {
            litDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _litProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _litProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Lit: {
                    changed = _litProperty.Read(stream, context);
                    if (changed) FireLitDidChange(lit);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _lit = lit;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
